sudo: required
dist: trusty
language: python
python:
  - 3.5.5
  - 2.7.6
virtualenv:
  system_site_package: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-opencv
  - sudo apt-get install -y cython
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python3.5
  - sudo apt-get update
install:
  - echo $TRAVIS_PYTHON_VERSION
  - pip install -U pip
  - pip install requests[security]
  - pip install pytest==3.6.1
  - pip install pep8==1.7.0
  - pip install -U pytest-cov
  - pip install --upgrade pip setuptools wheel
  - pip install entrypoints
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install Cython
  - pip install git+https://github.com/lucasb-eyer/pydensecrf.git
  - pip install tensorflow==1.8.0
  - pip install opencv-python
  - python setup.py install

script:
  - python -m unittest discover tests/
  - bash tools/ci_build/ci_sanity.sh

matrix:
fast_finish: true
