site_name: Tefla
repo_url: https://github.com/n3011/tefla
site_description: Documentation for Tefla, a deep learning library featuring a higher-level API for TensorFlow.
site_author: Mrinal(Ishant) Haloi

theme: readthedocs
docs_dir: templates

pages:
- Home: index.md
- Index: index.md
- Installation: installation.md
- Layers:
  - Layers: core/layers.md
  - RNN: core/rnn_cell.md
  - Special Layers: core/special_layers.md
  - Layer Args: core/layer_arg_ops.md
- Learner:
  - Learner: core/training.md
  - Learner Multi GPU: core/learning.md
  - Learner Multi GPU V2: core/learning_v2.md
  - Learner Semi Supervised: core/learning_ss.md
- Predictor:
  - Predictor: core/prediction.md
- Built-in Ops:
  - Lr_Policy: core/lr_policy.md
  - Metrics: core/metrics.md
  - Initializations: core/initializers.md
  - Losses: core/losses.md
  - Summaries: core/summary.md
  - Logger: core/logger.md
  - Iter Ops: core/iter_ops.md
- Data Management:
  - Data Augmentation: da/data.md
  - Standardizer: da/standardizer.md
  - TfRecords: dataset/image_to_tfrecords.md
  - Dataset: dataset/base.md
  - Dataflow: dataset/dataflow.md
  - Decoder: dataset/decoder.md
  - Reader: dataset/reader.md
- Utils:
  - Utils: utils/util.md
- License: license.md
